# Generated by Django 5.2 on 2026-03-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('therapist', 'Терапевт'), ('surgeon', 'Хирург'), ('cardiologist', 'Кардиолог'), ('dermatologist', 'Дерматолог'), ('neurologist', 'Невролог'), ('pediatrician', 'Педиатр'), ('psychiatrist', 'Психиатр'), ('radiologist', 'Радиолог'), ('anesthesiologist', 'Анестезиолог'), ('ophthalmologist', 'Офтальмолог'), ('gynecologist', 'Гинеколог'), ('urologist', 'Уролог'), ('endocrinologist', 'Эндокринолог')], max_length=50),
        ),
    ]
